### ISSUE TITLE
kfp部署相关镜像

### ISSUE THREAD

**Issue by wptoux** [x-mirrors/gcr.io#1]
除ml-pipelines中的相关镜像外，kfp部署似乎还需要如下镜像，能否一并同步，多谢~

gcr.io/tfx-oss-public/ml_metadata_store_server
gcr.io/cloudsql-docker/gce-proxy

**Comment by xiexianbin** [comment]
稍等，晚点处理

**Comment by xiexianbin** [comment]
@wptoux 
https://mirrors.kb.cx/?s=ml_metadata_store_server
https://mirrors.kb.cx/?s=gce-proxy
