### ISSUE TITLE
quayioceph/csi-cephfs:v3.8.0

### ISSUE THREAD

**Issue by Aurorxa** [x-mirrors/gcr.io#11]
docker pull quayioceph/csi-cephfs:v3.8.0 拉取不到，Docker Hub 仓库不存在，麻烦了~~~

**Comment by xiexianbin** [comment]
源里面没有这个镜像 https://quay.io/repository/ceph/csi-cephfs?tab=tags&tag=latest

**Comment by Aurorxa** [comment]
哈哈，我怀疑是我看错了，尴尬了。
