### ISSUE TITLE
k8s.gcr.io 镜像 mirror 已经产生差异了。

### ISSUE THREAD

**Issue by soulmz** [x-mirrors/gcr.io#16]
kubernetes v1.25 容器注册服务由 k8s.gcr.io 迁移到 registry.k8s.io

建议 保留 k8s.gcr.io -> k8sgcriosigstorage/csi-attacher

新增 registry.k8s.io 同步 mirror registryk8ssigstorage/csi-attacher

上面的 k8sgcriosigstorage/csi-attacher 最新的版本只有 4.2.0 很久之前了。

registry.k8s.io 已经存在 4.3.0 了。

当然其他的库也一并同步

**Comment by estack** [comment]
收到，我找时间处理





来自阿里邮箱Android客户端------------------------------------------------------------------
***@***.***>
日　期：2023年11月15日 09:48:25
***@***.***>
***@***.***>
主　题：[x-mirrors/gcr.io] k8s.gcr.io 镜像 mirror 已经产生差异了。 (Issue #16)

kubernetes v1.25 容器注册服务由 k8s.gcr.io 迁移到 registry.k8s.io
建议 保留 k8s.gcr.io -> k8sgcriosigstorage/csi-attacher
新增 registry.k8s.io 同步 mirror registryk8ssigstorage/csi-attacher
上面的 k8sgcriosigstorage/csi-attacher 最新的版本只有 4.2.0 很久之前了。
registry.k8s.io 已经存在 4.3.0 了。
当然其他的库也一并同步

**Comment by xiexianbin** [comment]
1. registry.k8s.io 同步已经到最新
2. registry.k8s.io/sig-storage/csi-attacher
-  最新同步地址为：https://hub.docker.com/r/registryk8s/sig-storage-csi-attacher/tags
- 搜索地址为：https://mirrors.kb.cx/?s=storage-csi-attache?s=sig-storage-csi-attache
