### ISSUE TITLE
tekton同步请求

### ISSUE THREAD

**Issue by myuid** [x-mirrors/gcr.io#7]
缺少gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/sidecarlogresults:v0.43.2@sha256:8c7e3dbb3cbfa76e9d291d869d50c93b4b9001dab6e3143d5db7b4e297144814镜像。

**Comment by xiexianbin** [comment]
https://mirrors.kb.cx/?s=sidecarlogresults
